# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TalentEdge' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TalentEdge


  pod 'Alamofire', '~> 4.4’
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Charts'
  target 'TalentEdgeTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['SWIFT_VERSION'] = '2.2'
          end
      end
  end

end
